# Iterative Proportional Fitting Code Demo


Code from https://github.com/Dirguis/ipfn (IPFN package for Python).

In [1]:
from ipfn import ipfn
import numpy as np
import pandas as pd
census_data_selected = pd.read_excel('planning_database_NYC_tracts_numbers.xlsx')
census_data_selected

Tract         Neighborhood  Tot_Population_CEN_2010  Pop_under_5_CEN_2010  \
0  19701  Morningside Heights                      641                    42   
1  19900  Morningside Heights                    10064                   316   
2  20101  Morningside Heights                     1731                    36   
3  20300  Morningside Heights                     3633                    62   
4  20500  Morningside Heights                     5322                   173   
5  20701  Morningside Heights                     3329                   113   
6  20901  Morningside Heights                     3673                   212   
7  21100  Morningside Heights                    10330                   430   

   Pop_5_17_CEN_2010  Pop_18_24_CEN_2010  Pop_25_44_CEN_2010  \
0                 59                  58                 331   
1                660                2974                3105   
2                 54                1153                 269   
3                 90                2210                1076   
4                305                2419                1006   
5                107                 760                1765   
6                692                 455                 931   
7               1084                1483                3669   

   Pop_45_64_CEN_2010  Pop_65plus_CEN_2010  Hispanic_CEN_2010  \
0                 116                   35                 90   
1                1711                 1298               1315   
2                 139                   80                211   
3                 120                   75                512   
4                 879                  540                529   
5                 375                  209                342   
6                 857                  526               1632   
7                2275                 1389               2734   

   NH_White_alone_CEN_2010  NH_Blk_alone_CEN_2010  NH_AIAN_alone_CEN_2010  \
0                      331                    102                       2   
1                     6001                    655                      12   
2                      907                    143                       4   
3                     1713                    354                       6   
4                     3428                    347                      11   
5                     2015                    181                       4   
6                      164                   1664                       4   
7                     3829                   2099                      35   

   NH_Asian_alone_CEN_2010  NH_NHOPI_alone_CEN_2010  NH_SOR_alone_CEN_2010  \
0                      100                        0                      4   
1                     1692                        7                     25   
2                      382                        2                      7   
3                      877                        3                      9   
4                      798                        4                     32   
5                      659                        3                     15   
6                      127                        1                     13   
7                     1334                        2                     36   

   Pop_Multiple  Renter_Occp_HU_CEN_2010  Owner_Occp_HU_CEN_2010  
0            12                      641                       0  
1           357                     7392                    2672  
2            75                     1477                     254  
3           159                     3502                     131  
4           173                     4348                     974  
5           110                     3191                     138  
6            68                     3499                     174  
7           261                     7645                    2685

In [2]:
df_tot = census_data_selected['Tot_Population_CEN_2010']
df_tot # total = 38723

0      641
1    10064
2     1731
3     3633
4     5322
5     3329
6     3673
7    10330
Name: Tot_Population_CEN_2010, dtype: int64

In [3]:
df_rent = census_data_selected[['Renter_Occp_HU_CEN_2010', 'Owner_Occp_HU_CEN_2010']]
df_rent

Renter_Occp_HU_CEN_2010  Owner_Occp_HU_CEN_2010
0                      641                       0
1                     7392                    2672
2                     1477                     254
3                     3502                     131
4                     4348                     974
5                     3191                     138
6                     3499                     174
7                     7645                    2685

In [130]:
df_race = census_data_selected[['Hispanic_CEN_2010','NH_White_alone_CEN_2010','NH_Blk_alone_CEN_2010','NH_AIAN_alone_CEN_2010','NH_Asian_alone_CEN_2010','NH_NHOPI_alone_CEN_2010','NH_SOR_alone_CEN_2010', 'Pop_Multiple']]
df_race

Hispanic_CEN_2010  NH_White_alone_CEN_2010  NH_Blk_alone_CEN_2010  \
0                 90                      331                    102   
1               1315                     6001                    655   
2                211                      907                    143   
3                512                     1713                    354   
4                529                     3428                    347   
5                342                     2015                    181   
6               1632                      164                   1664   
7               2734                     3829                   2099   

   NH_AIAN_alone_CEN_2010  NH_Asian_alone_CEN_2010  NH_NHOPI_alone_CEN_2010  \
0                       2                      100                        0   
1                      12                     1692                        7   
2                       4                      382                        2   
3                       6                      877                        3   
4                      11                      798                        4   
5                       4                      659                        3   
6                       4                      127                        1   
7                      35                     1334                        2   

   NH_SOR_alone_CEN_2010  Pop_Multiple  
0                      4            12  
1                     25           357  
2                      7            75  
3                      9           159  
4                     32           173  
5                     15           110  
6                     13            68  
7                     36           261

In [131]:
m = np.ones((len(df_race), len(df_race.columns), 2))
m_2 = np.zeros((len(df_race), len(df_race.columns), 2)) - 1e8
# all same for 1e-6
m_3 = np.zeros((len(df_race), len(df_race.columns), 2)) + 1e8
m.shape # track, race, rent

(8, 8, 2)

In [132]:
xipp = np.array(df_tot)
xijp = np.array(df_race)
xipk = np.array(df_rent)
xpjp = xijp.sum(axis=0)
xppk = xipk.sum(axis=0)

In [133]:
aggregates = [xipp, xpjp, xppk, xijp, xipk]
dimensions = [[0], [1], [2], [0, 1], [0, 2]]

In [134]:
IPF = ipfn.ipfn(m, aggregates, dimensions)
M = IPF.iteration()
print(xijp[0,0])
M_array = np.array(M)

90


/Users/noniethomas/Library/Python/3.7/lib/python/site-packages/ipfn/ipfn.py:129: RuntimeWarning: invalid value encountered in double_scalars
  if abs(m_ijk / ori_ijk - 1) > max_conv:


In [135]:
IPF_2 = ipfn.ipfn(m_2, aggregates, dimensions)
M_2 = IPF_2.iteration()
print(xijp[0,0])
M2_array = np.array(M_2)

90


/Users/noniethomas/Library/Python/3.7/lib/python/site-packages/ipfn/ipfn.py:129: RuntimeWarning: invalid value encountered in double_scalars
  if abs(m_ijk / ori_ijk - 1) > max_conv:


In [167]:
error_count = 0
tolerance = 1e-12
for i in range(M.shape[0]):
    if abs(M[i,:,:].sum() - xipp[i]) > tolerance:
        error_count += 1
    for j in range(M.shape[1]):
        if abs(M[i, j, :].sum() - xijp[i, j]) > tolerance:
            error_count += 1
    for k in range(M.shape[2]):
        if abs(M[i, :, k].sum() - xipk[i, k]) > tolerance:
            error_count += 1
for j in range(M.shape[1]):
    if abs(M[:,j,:].sum() - xpjp[j]) > tolerance:
        error_count += 1
for k in range(M.shape[2]):
    if abs(M[:,:,k].sum() - xppk[k]) > tolerance:
        error_count += 1

error_count

0

In [105]:
M == M_2

array([[[ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
      

In [107]:
M

array([[[9.17170111e+01, 0.00000000e+00],
        [3.37314785e+02, 0.00000000e+00],
        [1.03945946e+02, 0.00000000e+00],
        [2.03815580e+00, 0.00000000e+00],
        [1.01907790e+02, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00],
        [4.07631161e+00, 0.00000000e+00]],

       [[1.00138869e+03, 3.61973833e+02],
        [4.56983538e+03, 1.65186690e+03],
        [4.98790564e+02, 1.80298753e+02],
        [9.13814773e+00, 3.30318327e+00],
        [1.28847883e+03, 4.65748841e+02],
        [5.33058617e+00, 1.92685691e+00],
        [1.90378078e+01, 6.88163181e+00]],

       [[1.88192633e+02, 3.23635266e+01],
        [8.08960749e+02, 1.39117150e+02],
        [1.27542874e+02, 2.19335749e+01],
        [3.56763285e+00, 6.13526570e-01],
        [3.40708937e+02, 5.85917874e+01],
        [1.78381643e+00, 3.06763285e-01],
        [6.24335749e+00, 1.07367150e+00]],

       [[5.16126655e+02, 1.93068509e+01],
        [1.72680656e+03, 6.45949914e+01],
        [3.56853195e+02, 1.3

In [140]:
tract3 = M[2]

In [141]:
tract3.transpose()

array([[1.80038706e+02, 7.73910456e+02, 1.22016753e+02, 3.41305604e+00,
        3.25946852e+02, 1.70652802e+00, 5.97284806e+00, 6.39948007e+01],
       [3.09612940e+01, 1.33089544e+02, 2.09832467e+01, 5.86943963e-01,
        5.60531485e+01, 2.93471982e-01, 1.02715194e+00, 1.10051993e+01]])